### ISSUE TITLE
Java error running a report

### ISSUE THREAD

**Issue by malcolmfowler** [PHPJasper/phpjasper#162]
I am trying to port my reports from PHPJasperXML to PHPJasper and also move to a LINUX server. 

Installed using composer ... All OK
Java is installed

 I have successfully compiled a test report under linux using the example code as follows

`<?php
require __DIR__ . '/vendor/autoload.php';
use PHPJasper\PHPJasper;
$input = __DIR__ . '/reports/test1.jrxml';   
$jasper = new PHPJasper;
$jasper->compile($input)->execute();
?>`

Then set the executable directory...
sudo chmod +x /var/www/html/vendor/geekcom/phpjasper/bin/jasperstarter/bin

The trying to run the report using this code

`<?php
require __DIR__ . '/vendor/autoload.php';
use PHPJasper\PHPJasper;
$input = __DIR__ . '/reports/test1.jasper';  
$output = __DIR__ . '/printed_reports';    
$options = [
    'format' => ['pdf'],
    'locale' => 'en',
    'params' => [],
    'db_connection' => [
        'driver' => 'mysql',
        'username' => 'myUsername',
        'password' => 'myPassword',
        'host' => 'localhost',
        'database' => 'wms_mfsl',
        'port' => '3306'
    ]
];

$jasper = new PHPJasper;
$jasper->process(
    $input,
    $output,
    $options
)->execute();
?>`

The following error occurs in the browser..

> Fatal error: Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /var/www/html/vendor/geekcom/phpjasper/src/PHPJasper.php:219 Stack trace: #0 /var/www/html/test2.php(34): PHPJasper\PHPJasper->execute() #1 {main} thrown in /var/www/html/vendor/geekcom/phpjasper/src/PHPJasper.php on line 219

and when running PHP command line i see the following error.

> php /var/www/html/test2.php
Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:75)
	at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:65)
	at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:134)
	at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:151)
	at de.cenote.jasperstarter.App.processReport(App.java:178)
	at de.cenote.jasperstarter.App.main(App.java:109)
PHP Fatal error:  Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console. in /var/www/html/vendor/geekcom/phpjasper/src/PHPJasper.php:219
Stack trace:
#0 /var/www/html/test2.php(34): PHPJasper\PHPJasper->execute()
#1 {main}
  thrown in /var/www/html/vendor/geekcom/phpjasper/src/PHPJasper.php on line 219

**Here is the XML report definition from Jaspersoft studio.**
`<?xml version="1.0" encoding="UTF-8"?>

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="test1" pageWidth="595" pageHeight="842" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="4796d332-a186-4540-992f-f93517d46edb">
	<property name="com.jaspersoft.studio.data.defaultdataadapter" value="WMS"/>
	<property name="com.jaspersoft.studio.data.sql.tables" value=""/>
	<queryString>
		<![CDATA[select id, awb_pfx,awb_number
 from consignments]]>
	</queryString>
	<field name="id" class="java.lang.Integer">
		<property name="com.jaspersoft.studio.field.label" value="id"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="consignments"/>
	</field>
	<field name="awb_pfx" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.label" value="awb_pfx"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="consignments"/>
	</field>
	<field name="awb_number" class="java.lang.String">
		<property name="com.jaspersoft.studio.field.label" value="awb_number"/>
		<property name="com.jaspersoft.studio.field.tree.path" value="consignments"/>
	</field>
	<background>
		<band splitType="Stretch"/>
	</background>
	<title>
		<band height="40" splitType="Stretch"/>
	</title>
	<pageHeader>
		<band height="35" splitType="Stretch"/>
	</pageHeader>
	<columnHeader>
		<band height="39" splitType="Stretch">
			<staticText>
				<reportElement x="10" y="0" width="100" height="30" uuid="d536ec97-e0f1-4a39-b65e-eb93e194e134">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="8f2890e8-37ce-45c2-864e-c1b9056487e8"/>
				</reportElement>
				<text><![CDATA[id]]></text>
			</staticText>
			<staticText>
				<reportElement x="124" y="0" width="100" height="30" uuid="a4a07d06-7f5e-4df9-a08f-3b14e0be706a">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="73e2a9c3-0681-4cec-91bc-8030fadc8531"/>
				</reportElement>
				<text><![CDATA[awb_pfx]]></text>
			</staticText>
			<staticText>
				<reportElement x="235" y="0" width="100" height="30" uuid="d449af6f-3bf9-49a0-bf19-862f1018f306">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="a043fd6a-5f35-4873-b585-fc03c7e91fe5"/>
				</reportElement>
				<text><![CDATA[awb_number]]></text>
			</staticText>
		</band>
	</columnHeader>
	<detail>
		<band height="32" splitType="Stretch">
			<textField>
				<reportElement x="10" y="0" width="100" height="30" uuid="437f83b5-553e-4d48-a30d-5e38a7876346">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="8f2890e8-37ce-45c2-864e-c1b9056487e8"/>
				</reportElement>
				<textFieldExpression><![CDATA[$F{id}]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement x="124" y="0" width="100" height="30" uuid="76a9e65d-47f8-413c-a2ee-055ea4f8ae2c">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="73e2a9c3-0681-4cec-91bc-8030fadc8531"/>
				</reportElement>
				<textFieldExpression><![CDATA[$F{awb_pfx}]]></textFieldExpression>
			</textField>
			<textField>
				<reportElement x="236" y="1" width="100" height="30" uuid="8b136378-5514-4062-8cae-dec5fcbc8cd8">
					<property name="com.jaspersoft.studio.spreadsheet.connectionID" value="a043fd6a-5f35-4873-b585-fc03c7e91fe5"/>
				</reportElement>
				<textFieldExpression><![CDATA[$F{awb_number}]]></textFieldExpression>
			</textField>
		</band>
	</detail>
	<columnFooter>
		<band height="45" splitType="Stretch"/>
	</columnFooter>
	<pageFooter>
		<band height="54" splitType="Stretch"/>
	</pageFooter>
	<summary>
		<band height="42" splitType="Stretch"/>
	</summary>
</jasperReport>
`
Any guidance on what I am doing wrong?

Thanks
Malcolm

**Comment by malcolmfowler** [comment]
FYI - I have just run this on a windows server and all works as expected.
