### ISSUE TITLE
Ao gerar ta dando erro de fonte, mais não sei como corrigir é um windows server e as fontes do relatório estão no windows

### ISSUE THREAD

**Issue by Danillosdd** [PHPJasper/phpjasper#188]
at net.sf.jasperreports.engine.fonts.SimpleFontFace.loadFont(SimpleFontFace.java:198)
        ... 22 more
09:19:28,880 ERROR SimpleFontExtensionHelper:264 - Error loading font family
net.sf.jasperreports.engine.fonts.InvalidFontException: Error loading font "net/sf/jasperreports/fonts/icons/icons.ttf".
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.loadFont(SimpleFontFace.java:206)
        at net.sf.jasperreports.engine.fonts.SimpleFontFace.setTtf(SimpleFontFace.java:167)

**Comment by Danillosdd** [comment]
não deu erro mais, rs.. não sei o que aconteceu
