### ISSUE TITLE
Uncaught PHPJasper\Exception\ErrorCommandExecutable

### ISSUE THREAD

**Issue by xleriox** [PHPJasper/phpjasper#197]
Hello, I am doing tests with the library but at the time of execution it shows me the following error. if you can help me with it and how to fix it

 Uncaught PHPJasper\Exception\ErrorCommandExecutable: Your report has an error and couldn 't be processed!\ Try to output the command using the function `output();` and run it manually in the console.

**Comment by geekcom** [comment]
please try to run the `output();` method in jasperstarer console, to more informations about errors.

**Comment by xleriox** [comment]
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: net/sf/jasperreports/engine/JRException
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: net.sf.jasperreports.engine.JRException
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more

**Comment by xleriox** [comment]
shows this error when running on the console, the .jar has already been copied to JDBC

jasperstarter --locale en process "/rpt/ejemplo.jrxml" -o "/rpt" -f pdf -t generic -H 192.168.2.10 --db-port 1433 -n Jardin_DB -u sa -p jd1*19 --db-driver com.microsoft.sqlserver.jdbc.SQLServerDriver --db-url jdbc:sqlserver://192.168.2.10:1433;databaseName=Jardin_DB --jdbc-dir C:\wamp64\www\phpjasper/vendor/geekcom/phpjasper/bin/jaspertarter/jdbc
Error adding jdbc-dir

**Comment by djamara** [comment]
hi, please help me, jasperstarter don't run when I click. How to compile in console ??
