### ISSUE TITLE
Erro ao tentar gerar relatorio com QRCODE

### ISSUE THREAD

**Issue by claytonmlaia** [PHPJasper/phpjasper#201]
Boa tarde pessoal, preciso de ajuda.
Estou tentando utilizar um relatório criado pelo JasperStudio, o qual funciona perfeitamente em aplicações Java, no entanto quando colocamos para rodar com PHP, apresenta este erro de biblioteca. Ele contem um QRCode, e esta dando erro na biblioteca zxing, mesmo já tendo colocado ela no servidor. Alguém poderia ma ajudar com isso por favor? 
O erro é este abaixo:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/WriterException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:173)
        at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:131)
        at net.sf.jasperreports.engine.util.JRSingletonCache.createInstance(JRSingletonCache.java:87)
        at net.sf.jasperreports.engine.util.JRSingletonCache.getCachedInstance(JRSingletonCache.java:76)
        at net.sf.jasperreports.components.barcode4j.BarcodeUtils.getQRCodeProducer(BarcodeUtils.java:109)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcodeRenderable(AbstractBarcodeEvaluator.java:120)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.visitQRCode(AbstractBarcodeEvaluator.java:530)
        at net.sf.jasperreports.components.barcode4j.QRCodeComponent.receive(QRCodeComponent.java:73)
        at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcode(AbstractBarcodeEvaluator.java:85)
        at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluateBarcode(BarcodeFillComponent.java:83)
        at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluate(BarcodeFillComponent.java:70)
        at net.sf.jasperreports.engine.fill.JRFillComponentElement.evaluate(JRFillComponentElement.java:110)
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:548)
        at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillFixedBand(JRHorizontalFiller.java:2551)
        at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillDetail(JRHorizontalFiller.java:853)
        at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillReportStart(JRHorizontalFiller.java:264)
        at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillReport(JRHorizontalFiller.java:116)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:615)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:413)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:120)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)
        at de.cenote.jasperstarter.Report.fillInternal(Report.java:338)
        at de.cenote.jasperstarter.Report.fill(Report.java:282)
        at de.cenote.jasperstarter.App.processReport(App.java:226)
        at de.cenote.jasperstarter.App.main(App.java:109)
Caused by: java.lang.ClassNotFoundException: com.google.zxing.WriterException
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 30 more

**Comment by vcampos13** [comment]
Bom dia colega, conseguiu encontrar alguma solução, estou passando pelo mesmo problema.

**Comment by milewski** [comment]
Why are you guys talking in português... No one gonna help you if you post issues in português here...

**Comment by claytonmlaia** [comment]
Good afternoon guys, I need help.
I'm trying to use a report created by JasperStudio, or how it works perfectly in Java applications, however, when we run it with PHP, it presents this library error. It has a QRCode and is giving an error in the zxing library, but it is already placed on the server. Could someone help with that please?
The error is this below:

Exception in thread "main" java.lang.NoClassDefFoundError: com/google/zxing/WriterException
at java.lang.Class.forName0(Native Method)
at java.lang.Class.forName(Class.java:348)
at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForRealName(JRClassLoader.java:173)
at net.sf.jasperreports.engine.util.JRClassLoader.loadClassForName(JRClassLoader.java:131)
at net.sf.jasperreports.engine.util.JRSingletonCache.createInstance(JRSingletonCache.java:87)
at net.sf.jasperreports.engine.util.JRSingletonCache.getCachedInstance(JRSingletonCache.java:76)
at net.sf.jasperreports.components.barcode4j.BarcodeUtils.getQRCodeProducer(BarcodeUtils.java:109)
at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcodeRenderable(AbstractBarcodeEvaluator.java:120)
at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.visitQRCode(AbstractBarcodeEvaluator.java:530)
at net.sf.jasperreports.components.barcode4j.QRCodeComponent.receive(QRCodeComponent.java:73)
at net.sf.jasperreports.components.barcode4j.AbstractBarcodeEvaluator.evaluateBarcode(AbstractBarcodeEvaluator.java:85)
at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluateBarcode(BarcodeFillComponent.java:83)
at net.sf.jasperreports.components.barcode4j.BarcodeFillComponent.evaluate(BarcodeFillComponent.java:70)
at net.sf.jasperreports.engine.fill.JRFillComponentElement.evaluate(JRFillComponentElement.java:110)
at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:548)
at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillFixedBand(JRHorizontalFiller.java:2551)
at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillDetail(JRHorizontalFiller.java:853)
at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillReportStart(JRHorizontalFiller.java:264)
at net.sf.jasperreports.engine.fill.JRHorizontalFiller.fillReport(JRHorizontalFiller.java:116)
at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:615)
at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:413)
at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:120)
at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)
at de.cenote.jasperstarter.Report.fillInternal(Report.java:338)
at de.cenote.jasperstarter.Report.fill(Report.java:282)
at de.cenote.jasperstarter.App.processReport(App.java:226)
at de.cenote.jasperstarter.App.main(App.java:109)
Caused by: java.lang.ClassNotFoundException: com.google.zxing.WriterException
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)

**Comment by Tommendes** [comment]
And we keep don't knowing

**Comment by lecneri** [comment]
it may be a long shot, but did you add the lib to classpath?

**Comment by claytonmlaia** [comment]
Yes, but don't work.
