### ISSUE TITLE
Attribute 'textAdjust' is not allowed to appear in element 'textField'

### ISSUE THREAD

**Issue by Zaheer-Khawaja** [PHPJasper/phpjasper#253]
I have created a report with TIBCO Jaspersoft Studio 6.12.2.  The report is working fine in preview window.  The report has a Textfield with TextAdjust = "StretchHeight".
When I compile the report with Jaspersoft studio the .jasper file is created with no error.
But when I run the report using phpjasper the text field does not stretch.

When I tried to compile the report using phpjasper I get this error :
420 ERROR Digester:1770 - Parse Error at line 122 column 42: cvc-complex-type.3.2.2: Attribute 'textAdjust' is not allowed to appear in element 'textField'.
org.xml.sax.SAXParseException; lineNumber: 122; columnNumber: 42; cvc-complex-type.3.2.2: Attribute 'textAdjust' is not allowed to appear in element 'textField'.
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
        at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator$XSIErrorReporter.reportError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.reportSchemaError(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.processAttributes(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at org.apache.commons.digester.Digester.parse(Digester.java:1892)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:298)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.loadXML(JRXmlLoader.java:285)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:274)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:219)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:194)
        at net.sf.jasperreports.engine.xml.JRXmlLoader.load(JRXmlLoader.java:185)
        at de.cenote.jasperstarter.Report.<init>(Report.java:178)
        at de.cenote.jasperstarter.App.compile(App.java:141)
        at de.cenote.jasperstarter.App.main(App.java:105)

jrxml file is attached for reference.
[r_coa.zip](https://github.com/PHPJasper/phpjasper/files/4790894/r_coa.zip)

**Comment by tauanmarcel** [comment]
I have the same problem. My report also doesn't work in PHPJasper when I use the "Text Adjust" property as "**StretchHeight**" or "**ScaleFont**" in Jasper Studio.
I'm using JasperReports 6.12.2

**Comment by tauanmarcel** [comment]
I just found a solution for me, downgraded the jasper studio to version 6.8, and checked the option Stretch With Overflow for the field I wanted and so it worked on PHP Jasper

**Comment by Zaheer-Khawaja** [comment]
Thanks for help.  I downgraded jasper studio to 6.10.0 and the problem was fixed.  I think jasperstarter needs to be updated to accommodate this textadjust change, because in jasper studio 6.12.2 there is no compilation error and preview is also fine.

**Comment by geekcom** [comment]
Hi @Zaheer-Khawaja thanks for your issue, please open a issue on the https://bitbucket.org/cenote/jasperstarter/src/master/
