### ISSUE TITLE
Basic report will not load in Jasperstarter

### ISSUE THREAD

**Issue by malcolmfowler** [PHPJasper/phpjasper#268]
I created and compiled a simple report in Jaspersoft Studio. (Just Static text in header and detail bands) (XML below)

Any pointers to the problem would be appreciated 

Windows version 10

Java version  = E:\xampp\htdocs\report_testing\vendor\geekcom\phpjasper\bin\jasperstarter\bin>javac -version
javac 15.0.1

When I try to execute the report in Jaspestarter I have the following error.

E:\xampp\htdocs\report_testing\vendor\geekcom\phpjasper\bin\jasperstarter\bin>jasperstarter process "e:\xampp\htdocs\report_testing\rep1.jasper -o "e:\xampp\htdocs\report_testing\" -f pdf

Exception in thread "main" java.lang.ClassCastException: class jdk.internal.loader.ClassLoaders$AppClassLoader cannot be cast to class java.net.URLClassLoader (jdk.internal.loader.ClassLoaders$AppClassLoader and java.net.URLClassLoader are in module java.base of loader 'bootstrap')
        at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:75)
        at de.cenote.tools.classpath.ApplicationClasspath.add(ApplicationClasspath.java:65)
        at de.cenote.tools.classpath.ApplicationClasspath.addJars(ApplicationClasspath.java:134)
        at de.cenote.tools.classpath.ApplicationClasspath.addJarsRelative(ApplicationClasspath.java:151)
        at de.cenote.jasperstarter.App.processReport(App.java:178)
        at de.cenote.jasperstarter.App.main(App.java:109)

<?xml version="1.0" encoding="UTF-8"?>

<jasperReport xmlns="http://jasperreports.sourceforge.net/jasperreports" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://jasperreports.sourceforge.net/jasperreports http://jasperreports.sourceforge.net/xsd/jasperreport.xsd" name="Blank_A4" pageWidth="595" pageHeight="842" columnWidth="555" leftMargin="20" rightMargin="20" topMargin="20" bottomMargin="20" uuid="076ab8a6-d22a-4006-8654-b6afc5e26881">
	<queryString>
		<![CDATA[]]>
	</queryString>
	<background>
		<band splitType="Stretch"/>
	</background>
	<title>
		<band height="79" splitType="Stretch">
			<staticText>
				<reportElement x="220" y="10" width="100" height="40" uuid="c26cf1b9-5808-454a-b42c-e518a82abaa5"/>
				<text><![CDATA[Test report]]></text>
			</staticText>
		</band>
	</title>
	<pageHeader>
		<band height="35" splitType="Stretch"/>
	</pageHeader>
	<columnHeader>
		<band height="61" splitType="Stretch"/>
	</columnHeader>
	<detail>
		<band height="125" splitType="Stretch">
			<staticText>
				<reportElement x="325" y="57" width="100" height="30" uuid="9f52010b-681b-4fde-9778-97b203b46f24"/>
				<text><![CDATA[Static Text]]></text>
			</staticText>
		</band>
	</detail>
	<columnFooter>
		<band height="45" splitType="Stretch"/>
	</columnFooter>
	<pageFooter>
		<band height="54" splitType="Stretch"/>
	</pageFooter>
	<summary>
		<band height="42" splitType="Stretch"/>
	</summary>
</jasperReport>

**Comment by dinhunzvi** [comment]
consider downgrading your jdk. i'm using java version "1.8.0_261" and my reports work fine

**Comment by jeffersonGlemos** [comment]
I spent hours with this problem, changing the PATH correctly to use Java 1.8. My problem was that I had another version of Java 11 installed, I removed it and it worked.
