### ISSUE TITLE
Class not found when loading object from InputStream

### ISSUE THREAD

**Issue by gutembergz** [PHPJasper/phpjasper#269]
Boa tarde a todos. Estou tentando criar um relatório com subrelatório e me deparei com o seguinte erro: "_Class not found when loading object from InputStream_". O mesmo funciona corretamente pelo Jasper Studio, sem problemas, mas ao executar pelo console, ocorre isto. Agradeço se alguém puder me indicar um caminho.

O comando output gerado é o seguinte: 

`jasperstarter --locale pt process "D:/wamp64/www/manager/contratos/arquivos/jasper/ads.jrxml" -o "D:/wamp64/www/manager/contratos/arquivos/pdf" -f pdf -P nome_usuario="User Name" titulo_relatorio="Google Ads" contrato="000000" -t mysql -u xxx -p xxx -H mysql.xxx.com.br -n xxx--db-port 3306 -r "D:/wamp64/www/manager/contratos/arquivos/jasper/resources" `

Já o report e o subreport simplifiquei ao máximo para eliminar possíveis erros de cor, tamanhos, conexão, etc, mas o erro permanece.
 
- Já alterei o Data Source Expression = $P{REPORT_DATA_SOURCE} e a Connection Expression = $P{REPORT_CONNECTION} nas configurações do subreport;
- Os arquivos estão compilados em jasper, na pasta resources;
- Caminhos absolutos dos subreports são informados;
- Alterei as versões dos arquivos para versões mais antigas e mais novas;
- Não há imagens, classes extras ou nada de excepcional;
- Ao remover apenas os dados do Data Source Expression, o report abre sem erros, logicamente, sem o subreport.

**Abaixo seguem as configurações do subreport:**
```
<subreport isUsingCache="false" overflowType="NoStretch">
<reportElement key="" mode="Opaque" x="0" y="1" width="554" height="330" forecolor="#FFFFFF" backcolor="#FFFFFF" uuid="dd170da7-e79c-4b0b-97fa-b21fd05eb636">
<property name="com.jaspersoft.studio.element.name" value="HELP"/>
</reportElement>
<dataSourceExpression><![CDATA[$P{REPORT_DATA_SOURCE}]]></dataSourceExpression>
<subreportExpression><![CDATA["adsResponsivos.jasper"]]></subreportExpression>
</subreport>
```
**E esta é a lista de erros exibida quando executamos pelo command:**

```
Exception in thread "main" net.sf.jasperreports.engine.JRRuntimeException: net.sf.jasperreports.engine.JRException: Class not found when loading object from InputStream.
        at net.sf.jasperreports.repo.SerializedObjectPersistenceService.load(SerializedObjectPersistenceService.java:66)
        at net.sf.jasperreports.repo.SerializedReportPersistenceService.load(SerializedReportPersistenceService.java:46)
        at net.sf.jasperreports.repo.DefaultRepositoryService.getResource(DefaultRepositoryService.java:196)
        at net.sf.jasperreports.repo.RepositoryUtil.getResourceFromLocation(RepositoryUtil.java:149)
        at net.sf.jasperreports.repo.RepositoryUtil.getReport(RepositoryUtil.java:117)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.loadReport(JRFillSubreport.java:470)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.loadReportSource(JRFillSubreport.java:435)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.evaluateReportSource(JRFillSubreport.java:386)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.evaluateSubreport(JRFillSubreport.java:499)
        at net.sf.jasperreports.engine.fill.JRFillSubreport.evaluate(JRFillSubreport.java:350)
        at net.sf.jasperreports.engine.fill.JRFillElementContainer.evaluate(JRFillElementContainer.java:383)
        at net.sf.jasperreports.engine.fill.JRFillBand.evaluate(JRFillBand.java:548)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillColumnBand(JRVerticalFiller.java:2583)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillDetail(JRVerticalFiller.java:813)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReportStart(JRVerticalFiller.java:264)
        at net.sf.jasperreports.engine.fill.JRVerticalFiller.fillReport(JRVerticalFiller.java:110)
        at net.sf.jasperreports.engine.fill.JRBaseFiller.fill(JRBaseFiller.java:615)
        at net.sf.jasperreports.engine.fill.BaseReportFiller.fill(BaseReportFiller.java:413)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:120)
        at net.sf.jasperreports.engine.fill.JRFiller.fill(JRFiller.java:103)
        at net.sf.jasperreports.engine.JasperFillManager.fill(JasperFillManager.java:530)
        at net.sf.jasperreports.engine.JasperFillManager.fillReport(JasperFillManager.java:954)
        at de.cenote.jasperstarter.Report.fillInternal(Report.java:338)
        at de.cenote.jasperstarter.Report.fill(Report.java:282)
        at de.cenote.jasperstarter.App.processReport(App.java:226)
        at de.cenote.jasperstarter.App.main(App.java:109)
Caused by: net.sf.jasperreports.engine.JRException: Class not found when loading object from InputStream.
        at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:290)
        at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:262)
        at net.sf.jasperreports.repo.SerializedObjectPersistenceService.load(SerializedObjectPersistenceService.java:62)
        ... 25 more
Caused by: java.lang.ClassNotFoundException: net.sf.jasperreports.compilers.ReportExpressionEvaluationData
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Unknown Source)
        at java.io.ObjectInputStream.resolveClass(Unknown Source)
        at net.sf.jasperreports.engine.util.ContextClassLoaderObjectInputStream.resolveClass(ContextClassLoaderObjectInputStream.java:89)
        at java.io.ObjectInputStream.readNonProxyDesc(Unknown Source)
        at java.io.ObjectInputStream.readClassDesc(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.defaultReadFields(Unknown Source)
        at java.io.ObjectInputStream.readSerialData(Unknown Source)
        at java.io.ObjectInputStream.readOrdinaryObject(Unknown Source)
        at java.io.ObjectInputStream.readObject0(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at java.io.ObjectInputStream.readObject(Unknown Source)
        at net.sf.jasperreports.engine.util.JRLoader.loadObject(JRLoader.java:278)
        ... 27 more
```

**Comment by jer0256** [comment]
Hi, did you solved this problem? im also experiencing the same problem when generating report with subreport with JSON data source.

My report is working fine in jasper studio also but when i try with phpjasper, i also experiencing the exact error

**Comment by gutembergz** [comment]
Hi - I did'nt solved this issue. I tried to work it around, but I haven't any success. I tried to use even a empty sub report, with no data source. Just like you, my report works fine only with jasper soft studio.

If anyone can help us, I appreciate.

**Comment by jer0256** [comment]
Hi - my goal for using sub report is to access nested stucture of my data source (JSON), i found a work around by using dataset and list in jasper studio.

**Comment by ksx501** [comment]
have you guys soloved it yet?

**Comment by gutembergz** [comment]
> have you guys soloved it yet?

Hi! After several tests, I found where I was missing. Just **compile the subreport to jasper files with the jasperstarter instead using the Jaspersoft Studio Compiler**. I tested using older versions of compiler and files, but I didn't succeed. 

Use the compiler through the console/command of jasperstarter;  or compile the jasper files through phpjasper.

`jasperstarter compile "C:/reports/resources/subreport.jrxml"`
